name: Test Ref

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: echo ${{ github.event.pull_request.head.sha }}
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.event.ref }}

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0
