name: Test Ref

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.event.pull_request.head.ref }}
      - run: echo ${{ github.event.pull_request.head.sha }}
      - run: echo ${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - run: npx @aneoconsultingfr/generate-next-version --edge
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - run: npx @aneoconsultingfr/generate-next-version --edge
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - run: npx @aneoconsultingfr/generate-next-version --edge
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - run: npx @aneoconsultingfr/generate-next-version --edge
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - run: npx @aneoconsultingfr/generate-next-version --edge
